name: Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug = Pixeldrain only, test = + GitHub release, release = + OTA XML)'
        type: choice
        options:
          - debug
          - test
          - release
        default: debug
  pull_request:
  push:
    branches:
      - 'sixteen'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        target: [t2s]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          submodules: 'recursive'

      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            attr ccache clang ffmpeg libbrotli-dev libbz2-dev \
            libgtest-dev libprotobuf-dev libunwind-dev libpcre2-dev \
            libzstd-dev linux-modules-extra-$(uname -r) lld protobuf-compiler webp \
            build-essential g++-aarch64-linux-gnu gcc-aarch64-linux-gnu python-is-python3 python3 wget
          wget https://raw.githubusercontent.com/kdrag0n/kramflash/refs/heads/master/mkbootimg.py && sudo ln -sf $(pwd)/mkbootimg.py /usr/bin/mkbootimg && chmod +x /usr/bin/mkbootimg
          sudo modprobe erofs f2fs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo -n "${{ secrets.PLATFORM_KEY_PK8 }}" | base64 --decode > security/artisanrom_platform.pk8
          echo -n "${{ secrets.PLATFORM_KEY_PEM }}" | base64 --decode > security/artisanrom_platform.x509.pem
          echo -n "${{ secrets.OTA_KEY_PK8 }}" | base64 --decode > security/artisanrom_ota.pk8
          echo -n "${{ secrets.OTA_KEY_PEM }}" | base64 --decode > security/artisanrom_ota.x509.pem

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build dependencies
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/build_dependencies.sh

      - name: Download stock firmwares
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_on: error
          command: source ./buildenv.sh ${{ matrix.target }} && ./scripts/download_fw.sh

      - name: Extract stock firmwares
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/extract_fw.sh
      
      - name: Build ROM
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/make_rom.sh 
          
      - name: Upload to GoFile
        run: |
          ZIP_FILE=$(find out -maxdepth 1 -type f -name "*.zip" | head -n 1)

          RESPONSE=$(curl -s -F "file=@$ZIP_FILE" -F "token=${{ secrets.GOFILE_TOKEN }}" -F "folderId=${{ secrets.GOFILE_FOLDER_ID }}" "https://upload-eu-par.gofile.io/uploadFile")

          echo "Uploaded successfully! Download link:"
          echo "$RESPONSE" | jq -r '.data.downloadPage'

          echo "MD5:"
          md5sum "$ZIP_FILE"

          echo "SHA256:"
          sha256sum "$ZIP_FILE"
